import type { AiReviewEnv } from "./ai-review.ts";

export function sharedAiReviewEnv(env: AiReviewEnv): AiReviewEnv {
  return {
    GITHUB_READ_TOKEN: env.GITHUB_READ_TOKEN,
    AI_REVIEW_GATEWAY_TOKEN: env.AI_REVIEW_GATEWAY_TOKEN,
    AI_REVIEW_POLICY_REF: env.AI_REVIEW_POLICY_REF,
    AI_PROVIDER_MINIMAX_CN_CODEPLAN_KEY: env.AI_PROVIDER_MINIMAX_CN_CODEPLAN_KEY,
    AI_PROVIDER_VOLCENGINE_CODING_PLAN_KEY: env.AI_PROVIDER_VOLCENGINE_CODING_PLAN_KEY,
    AI_PROVIDER_OPENCODE_GO_KEY: env.AI_PROVIDER_OPENCODE_GO_KEY,
  };
}
