import type { AiReviewEnv } from "./ai-review.ts";

export function sharedAiReviewEnv(env: AiReviewEnv): AiReviewEnv {
  return {
    GITHUB_READ_TOKEN: env.GITHUB_READ_TOKEN,
    AI_REVIEW_GATEWAY_TOKEN: env.AI_REVIEW_GATEWAY_TOKEN,
    AI_REVIEW_POLICY_REF: env.AI_REVIEW_POLICY_REF,
    AI_REVIEW_PRIMARY_ID: env.AI_REVIEW_PRIMARY_ID,
    AI_REVIEW_PRIMARY_ENDPOINT: env.AI_REVIEW_PRIMARY_ENDPOINT,
    AI_REVIEW_PRIMARY_API_KEY: env.AI_REVIEW_PRIMARY_API_KEY,
    AI_REVIEW_PRIMARY_MODEL: env.AI_REVIEW_PRIMARY_MODEL,
    AI_REVIEW_PRIMARY_RESPONSE_FORMAT: env.AI_REVIEW_PRIMARY_RESPONSE_FORMAT,
    AI_REVIEW_PRIMARY_MAX_PROMPT_CHARACTERS: env.AI_REVIEW_PRIMARY_MAX_PROMPT_CHARACTERS,
    AI_REVIEW_PRIMARY_MAX_OUTPUT_TOKENS: env.AI_REVIEW_PRIMARY_MAX_OUTPUT_TOKENS,
    AI_REVIEW_PRIMARY_OUTPUT_TOKEN_PARAMETER: env.AI_REVIEW_PRIMARY_OUTPUT_TOKEN_PARAMETER,
    AI_REVIEW_FALLBACK_ID: env.AI_REVIEW_FALLBACK_ID,
    AI_REVIEW_FALLBACK_ENDPOINT: env.AI_REVIEW_FALLBACK_ENDPOINT,
    AI_REVIEW_FALLBACK_API_KEY: env.AI_REVIEW_FALLBACK_API_KEY,
    AI_REVIEW_FALLBACK_MODEL: env.AI_REVIEW_FALLBACK_MODEL,
    AI_REVIEW_FALLBACK_RESPONSE_FORMAT: env.AI_REVIEW_FALLBACK_RESPONSE_FORMAT,
    AI_REVIEW_FALLBACK_MAX_PROMPT_CHARACTERS: env.AI_REVIEW_FALLBACK_MAX_PROMPT_CHARACTERS,
    AI_REVIEW_FALLBACK_MAX_OUTPUT_TOKENS: env.AI_REVIEW_FALLBACK_MAX_OUTPUT_TOKENS,
    AI_REVIEW_FALLBACK_OUTPUT_TOKEN_PARAMETER: env.AI_REVIEW_FALLBACK_OUTPUT_TOKEN_PARAMETER,
  };
}
